"""
Pydantic response/request schemas for the REST API.

These define the JSON shape returned to the web dashboard and external API
consumers. They are separate from SQLAlchemy models so the API can evolve
independently of the database layer.
"""

from datetime import date, datetime

from pydantic import BaseModel, Field


class ScheduleEntryOut(BaseModel):
    """One stored schedule row as returned by GET /api/schedules."""

    id: int
    date_header: str
    schedule_date: date
    ship: str
    checkin_time: str
    return_time: str
    boat_codes: str
    berth: str | None = None
    ship_count: int | None
    upload_batch_id: str
    created_at: datetime

    model_config = {"from_attributes": True}


class ScheduleEntryUpdate(BaseModel):
    """Editable fields for PATCH /api/schedules/{entry_id}."""

    checkin_time: str | None = None
    return_time: str | None = None
    boat_codes: str | None = None


class ScheduleEntryCreate(BaseModel):
    """Fields for POST /api/schedules to add a new tour manually."""

    schedule_date: date
    ship: str
    checkin_time: str
    return_time: str
    boat_codes: str = ""
    berth: str | None = None
    date_header: str | None = None


class ScheduleBulkCreate(BaseModel):
    """Paste dispatch-style tour lines for one day via POST /api/schedules/bulk."""

    schedule_date: date
    text: str
    use_ai: bool = True


class ScheduleBulkResult(BaseModel):
    """Summary returned after bulk tour import."""

    rows_parsed: int
    rows_created: int
    rows_merged: int
    rows_skipped: int
    errors: list[str] = []
    ai_assisted: bool = False
    ai_message: str | None = None


class UploadResult(BaseModel):
    """Summary returned after a successful XML upload."""

    batch_id: str
    filename: str
    rows_imported: int
    rows_skipped: int
    notes: str | None = None


class CaptainPrediction(BaseModel):
    """
    A forecasted captain shift on a future date.

    Generated by projecting learned day-of-week patterns forward, then applying
    scheduling constraints (one boat per ship, no overlaps, alphabetical dispatch,
    3-hour turnaround). When OpenAI is configured, AI may forecast ships in port
    and suggest assignments for uncovered vessels (source='ai').
    """

    boat_code: str
    schedule_date: date
    day_of_week: str
    ship: str
    checkin_time: str
    return_time: str
    confidence: float = Field(ge=0.0, le=1.0)
    passenger_estimate: int | None = None
    busy_score: float = Field(ge=0.0, le=1.0, description="How busy the day is expected to be")
    source: str = "pattern"


class AiPredictionMeta(BaseModel):
    """Metadata about whether AI contributed to a prediction response."""

    ai_assisted: bool = False
    ai_ship_forecasts: int = 0
    ai_captain_suggestions: int = 0
    message: str | None = None


class CaptainSummary(BaseModel):
    """Roll-up view of one captain's history and upcoming predicted shifts."""

    boat_code: str
    total_historical_shifts: int
    predicted_shifts: int
    next_shift: CaptainPrediction | None = None


class PredictionsResponse(BaseModel):
    """Predictions list with optional AI assistance metadata."""

    predictions: list[CaptainPrediction]
    ai: AiPredictionMeta


class CaptainSummariesResponse(BaseModel):
    """Captain overview list with optional AI assistance metadata."""

    captains: list[CaptainSummary]
    ai: AiPredictionMeta


class BusyCalendarResponse(BaseModel):
    """Busy-day calendar with optional AI assistance metadata."""

    calendar: list[dict]
    ai: AiPredictionMeta


class StatsOut(BaseModel):
    """High-level database statistics shown in the dashboard header."""

    total_entries: int
    unique_ships: int
    unique_captains: int
    date_range_start: date | None
    date_range_end: date | None
    uploads: int
    patterns_learned: int = 0
    last_upload_at: datetime | None = None
    has_stored_data: bool = False


class StorageStatusOut(BaseModel):
    """Persistence status — confirms data survives server restarts."""

    database_path: str
    data_dir: str
    total_entries: int
    uploads: int
    patterns_learned: int
    date_range_start: date | None
    date_range_end: date | None
    last_upload_at: datetime | None
    ready_for_predictions: bool
    message: str


class ShipCapacityOut(BaseModel):
    """Ship passenger capacity record for the ship registry API."""

    ship_name: str
    passenger_capacity: int
    cruise_line: str | None
    source: str

    model_config = {"from_attributes": True}


class RepairRecordOut(BaseModel):
    """One automated repair applied during XML cleaning."""

    entry_index: int
    field: str
    issue: str
    before: str
    after: str
    confidence: float = Field(ge=0.0, le=1.0)


class XmlCleanResult(BaseModel):
    """Output from the XML clean/repair pipeline."""

    cleaned_xml: str
    entries_processed: int
    times_normalized: int
    boat_fields_repaired: int
    parse_method: str
    ai_assisted: bool
    hour_distribution: dict[str, int]
    repairs: list[RepairRecordOut]
    warnings: list[str] = []
    errors: list[str] = []
