"""
Pydantic response/request schemas for the REST API.

These define the JSON shape returned to the web dashboard and external API
consumers. They are separate from SQLAlchemy models so the API can evolve
independently of the database layer.
"""

from datetime import date, datetime

from pydantic import BaseModel, Field


class ScheduleEntryOut(BaseModel):
    """One stored schedule row as returned by GET /api/schedules."""

    id: int
    date_header: str
    schedule_date: date
    ship: str
    checkin_time: str
    return_time: str
    boat_codes: str
    ship_count: int | None
    upload_batch_id: str
    created_at: datetime

    model_config = {"from_attributes": True}


class UploadResult(BaseModel):
    """Summary returned after a successful XML upload."""

    batch_id: str
    filename: str
    rows_imported: int
    rows_skipped: int
    notes: str | None = None


class CaptainPrediction(BaseModel):
    """
    A forecasted captain shift on a future date.

    Generated by projecting learned day-of-week patterns forward. Confidence
    reflects how consistently this captain has held this assignment historically.
    """

    boat_code: str
    schedule_date: date
    day_of_week: str
    ship: str
    checkin_time: str
    return_time: str
    confidence: float = Field(ge=0.0, le=1.0)
    passenger_estimate: int | None = None
    busy_score: float = Field(ge=0.0, le=1.0, description="How busy the day is expected to be")
    source: str = "pattern"


class CaptainSummary(BaseModel):
    """Roll-up view of one captain's history and upcoming predicted shifts."""

    boat_code: str
    total_historical_shifts: int
    predicted_shifts: int
    next_shift: CaptainPrediction | None = None


class StatsOut(BaseModel):
    """High-level database statistics shown in the dashboard header."""

    total_entries: int
    unique_ships: int
    unique_captains: int
    date_range_start: date | None
    date_range_end: date | None
    uploads: int


class ShipCapacityOut(BaseModel):
    """Ship passenger capacity record for the ship registry API."""

    ship_name: str
    passenger_capacity: int
    cruise_line: str | None
    source: str

    model_config = {"from_attributes": True}
